### ISSUE TITLE
リソース使用量チェックルールを追加

### ISSUE THREAD

**Issue by mmocchi** [mmocchi/pytestee#13]
## 概要
テスト実行時のメモリ・CPU使用量を監視し、効率的なテストコードの作成を促すルール

## 背景
- AI生成コードは大量データ生成・重い処理を含みがち
- CI環境でのリソース枯渇
- 開発マシンでのテスト実行負荷増大

### メモリ使用量
```python
# BAD: 大量メモリ消費
def test_large_dataset_processing():
    # 100万要素のリスト生成（約400MB）
    large_data = [{"id": i, "data": "x" * 100} for i in range(1000000)]
    result = process_dataset(large_data)
    assert len(result) > 0

# GOOD: 適切なサイズ
def test_dataset_processing():
    # 最小限のテストデータ
    test_data = [{"id": 1, "data": "sample"}]
    result = process_dataset(test_data)
    assert len(result) == 1
```

### CPU集約的処理
```python
# BAD: 重いCPU処理
def test_complex_calculation():
    # フィボナッチ数列を100万項まで計算
    for i in range(1000000):
        result = fibonacci(i)
    assert result > 0

# GOOD: モック化
@patch('module.fibonacci')
def test_complex_calculation(mock_fib):
    mock_fib.return_value = 12345
    result = fibonacci(100)
    assert result == 12345
```

### 大容量ファイル処理
```python
# BAD: 大容量ファイル生成
def test_file_processing():
    # 1GBのテストファイル作成
    with open("large_test_file.txt", "w") as f:
        for i in range(1000000):
            f.write("This is test line number %d\n" % i)
    
    result = process_large_file("large_test_file.txt")
    os.remove("large_test_file.txt")

# GOOD: 小さなサンプル
def test_file_processing(tmp_path):
    test_file = tmp_path / "small_test.txt"
    test_file.write_text("line1\nline2\nline3")
    
    result = process_file(str(test_file))
    assert len(result) == 3
```

### 無限ループ・長時間処理
```python
# BAD: 制御不能な処理
def test_monitoring_loop():
    start_time = time.time()
    while True:  # 無限ループリスク
        if monitor_condition():
            break
        if time.time() - start_time > 300:  # 5分でタイムアウト
            break
    assert True

# GOOD: 制御された処理
def test_monitoring_condition():
    with patch('module.monitor_condition') as mock_monitor:
        mock_monitor.return_value = True
        result = check_monitoring()
        assert result is True
```

### リソース監視メトリクス
```python
class ResourceUsageMetrics:
    peak_memory_mb: float        # ピークメモリ使用量（MB）
    avg_cpu_percent: float       # 平均CPU使用率
    execution_time_sec: float    # 実行時間（秒）
    file_io_operations: int      # ファイルI/O回数
    network_requests: int        # ネットワークリクエスト数
    temp_files_created: int      # 一時ファイル作成数
```

### 検出パターン
1. **大量データ生成**
   - リスト内包表記での大量要素生成
   - 巨大辞書・セットの作成
   - 大容量文字列の生成

2. **CPU集約的パターン**
   - ネストした深いループ
   - 再帰処理の深い呼び出し
   - 数学的計算の重い処理

3. **I/O集約的パターン**
   - 大容量ファイルの読み書き
   - 複数ファイルの同時処理
   - データベースでの大量クエリ

### 閾値設定
```yaml
resource_rules:
  memory:
    max_peak_mb: 100           # 最大メモリ使用量（MB）
    warn_peak_mb: 50           # 警告レベル（MB）
  cpu:
    max_cpu_percent: 80        # 最大CPU使用率
    max_execution_time: 5.0    # 最大実行時間（秒）
  io:
    max_file_operations: 10    # 最大ファイル操作回数
    max_temp_files: 5          # 最大一時ファイル数
  detection:
    large_list_threshold: 10000     # 大量リスト閾値
    deep_loop_threshold: 3          # 深いループ閾値
    heavy_calculation_patterns:     # 重い計算パターン
      - "fibonacci"
      - "factorial"
      - "prime_check"
```

### 監視実装
```python
import psutil
import time
from contextlib import contextmanager

@contextmanager
def monitor_resources():
    process = psutil.Process()
    start_memory = process.memory_info().rss / 1024 / 1024  # MB
    start_time = time.time()
    
    yield
    
    end_memory = process.memory_info().rss / 1024 / 1024
    execution_time = time.time() - start_time
    
    if end_memory - start_memory > 100:  # 100MB超過
        warnings.warn(f"High memory usage: {end_memory - start_memory:.1f}MB")
```

## 最適化提案
```
Resource Usage Warning: High memory consumption detected
- Peak memory: 250MB (threshold: 100MB)
- Execution time: 8.5s (threshold: 5.0s)

Suggestions:
1. Use smaller test datasets (current: 1M items, suggested: <1K items)
2. Mock heavy calculations instead of actual computation
3. Use streaming for large file processing
4. Consider pytest-benchmark for performance testing
```

## 優先度: MEDIUM
パフォーマンス改善に寄与するが、機能的影響は限定的

🤖 Generated with [Claude Code](https://claude.ai/code)
