### ISSUE TITLE
プロジェクト整合性チェックルールを追加

### ISSUE THREAD

**Issue by mmocchi** [mmocchi/pytestee#14]
## 概要
AI生成コードが既存プロジェクトの規約・パターンと整合しているかをチェックするルール

## 背景
- AI生成コードは既存プロジェクトのコンテキストを理解せず生成されがち
- チーム内での一貫性が損なわれる
- コードレビュー負荷増大

### 命名規則の整合性
```python
# 既存パターン分析
class TestUserService:
    def test_ユーザー作成_正常系(self):
        pass
    
    def test_ユーザー削除_権限エラー(self):
        pass

# BAD: 既存と異なる命名
def test_user_creation():           # 英語命名
    pass

class UserTest:                     # 異なるクラス命名パターン
    def testCreateUser(self):       # camelCase使用
        pass

# GOOD: 既存パターンに準拠
class TestUserService:
    def test_ユーザー作成_管理者権限(self):
        pass
```

### ディレクトリ構造の整合性
```python
# 既存構造
tests/
├── unit/
│   ├── test_user_service.py
│   └── test_product_service.py
├── integration/
│   └── test_api_endpoints.py

# BAD: 異なる構造
tests/
├── user_tests.py              # 既存パターンと異なる
├── integration_tests/         # 既存と異なる命名
│   └── api_test.py
```

### インポート・依存関係パターン
```python
# 既存パターン
from src.services.user_service import UserService
from src.models.user import User
from tests.fixtures.user_fixtures import create_test_user

# BAD: 異なるインポートパターン
import sys
sys.path.append('..')
from user_service import UserService  # 相対パス使用

# BAD: プロジェクトで使用しないライブラリ
import requests_mock  # プロジェクトでmockライブラリ未使用
```

### テストフレームワーク・ツール統一
```python
# プロジェクト標準: pytest + unittest.mock
import pytest
from unittest.mock import Mock, patch

# BAD: 異なるツール使用
import unittest              # プロジェクトはpytest使用
from mock import Mock        # 古いmockライブラリ
import nose.tools           # 使用しないテストツール
```

### 既存パターン学習
```python
class ProjectPatternAnalyzer:
    def analyze_naming_conventions(self, test_files: List[str]) -> Dict:
        patterns = {
            'class_naming': [],      # クラス命名パターン
            'method_naming': [],     # メソッド命名パターン
            'variable_naming': [],   # 変数命名パターン
            'language_preference': 'japanese/english',  # 言語選好
        }
        # AST解析で既存パターンを抽出
        return patterns
    
    def analyze_directory_structure(self) -> Dict:
        return {
            'test_directories': [],   # テストディレクトリ構造
            'file_naming': [],       # ファイル命名規則
            'organization_pattern': 'by_feature/by_type'
        }
    
    def analyze_dependencies(self) -> Dict:
        return {
            'import_patterns': [],    # インポートパターン
            'mock_library': 'unittest.mock/pytest-mock',
            'test_framework': 'pytest/unittest',
            'fixture_patterns': []   # フィクスチャー使用パターン
        }
```

### 整合性チェック機能
```python
class ConsistencyChecker:
    def check_naming_consistency(self, new_code: str, patterns: Dict) -> List[Issue]:
        issues = []
        
        # クラス命名チェック
        if patterns['class_naming'] == 'TestXXX' and 'XXXTest' in new_code:
            issues.append(Issue(
                'naming_inconsistency',
                'Class naming should follow TestXXX pattern'
            ))
        
        # 言語使用チェック
        if patterns['language_preference'] == 'japanese' and has_english_only_names(new_code):
            issues.append(Issue(
                'language_inconsistency', 
                'Use Japanese naming as per project convention'
            ))
        
        return issues
```

### 設定可能項目
```yaml
consistency_rules:
  enforce_naming_conventions: true
  enforce_directory_structure: true
  enforce_import_patterns: true
  enforce_dependency_consistency: true
  
  naming:
    class_pattern: "Test.*"           # 既存から自動検出
    method_pattern: "test_.*"
    language_preference: "japanese"   # japanese/english/mixed
    
  structure:
    test_directory_pattern: "tests/**"
    file_naming_pattern: "test_*.py"
    
  dependencies:
    allowed_mock_libraries: ["unittest.mock"]
    forbidden_imports: ["nose", "mock"]
    required_imports: ["pytest"]
```

### 学習・適応機能
```python
class PatternLearner:
    def learn_from_existing_code(self) -> ProjectPatterns:
        """既存コードから自動的にパターンを学習"""
        
    def suggest_improvements(self, inconsistencies: List[Issue]) -> List[Suggestion]:
        """整合性違反に対する改善提案"""
        
    def update_patterns(self, new_patterns: Dict):
        """新しいパターンの追加・更新"""
```

## 検出メッセージ例
```
Project Consistency Warning:
- Class naming inconsistency: Found 'UserTest' but project uses 'TestUser' pattern
- Language inconsistency: Method uses English names but project prefers Japanese
- Import pattern: Using 'from mock import Mock' but project uses 'unittest.mock'

Suggestions:
1. Rename 'UserTest' to 'TestUser'
2. Change 'test_user_creation' to 'test_ユーザー作成'
3. Replace 'from mock import Mock' with 'from unittest.mock import Mock'

Auto-fix available: Run `pytestee fix --consistency`
```

## 学習データ例
```json
{
  "project_patterns": {
    "naming": {
      "class_prefix": "Test",
      "method_prefix": "test_",
      "language": "japanese",
      "separator": "_"
    },
    "structure": {
      "test_root": "tests/",
      "unit_tests": "tests/unit/",
      "integration_tests": "tests/integration/"
    },
    "tools": {
      "test_framework": "pytest",
      "mock_library": "unittest.mock",
      "fixture_style": "pytest_fixtures"
    }
  }
}
```

## 優先度: MEDIUM
チーム開発の一貫性向上に重要だが、即座の機能影響は少ない

🤖 Generated with [Claude Code](https://claude.ai/code)
