### ISSUE TITLE
Python品質ルールを追加

### ISSUE THREAD

**Issue by mmocchi** [mmocchi/pytestee#19]
## 概要
モダンなPython記法・ベストプラクティスに準拠したテストコードの作成を促すルール

## 背景
- AI生成コードは古いPython記法を使用しがち
- 型ヒント、f-string等のモダン機能が未活用
- Pythonic でない冗長なコードが生成される

### 型ヒント不足
```python
# BAD: 型ヒント不足
def test_calculate_total():
    items = [{"price": 100}, {"price": 200}]     # List[Dict]が不明
    tax_rate = 0.1                               # float が不明
    result = calculate_total(items, tax_rate)    # 戻り値型不明
    assert result == 330

def helper_function(data):                       # 引数・戻り値型不明
    return data.get("value", 0)

# GOOD: 適切な型ヒント
def test_calculate_total():
    items: List[Dict[str, int]] = [{"price": 100}, {"price": 200}]
    tax_rate: float = 0.1
    result: float = calculate_total(items, tax_rate)
    assert result == 330.0

def helper_function(data: Dict[str, Any]) -> int:
    return data.get("value", 0)
```

### 古い文字列フォーマット
```python
# BAD: 古いフォーマット記法
def test_user_message():
    name = "Alice"
    age = 30
    
    # % フォーマット（Python 2時代）
    message1 = "User: %s, Age: %d" % (name, age)
    
    # .format()（Python 3.0-3.6）
    message2 = "User: {}, Age: {}".format(name, age)
    message3 = "User: {name}, Age: {age}".format(name=name, age=age)
    
    assert "Alice" in message1

# GOOD: f-string使用（Python 3.6+）
def test_user_message():
    name: str = "Alice"
    age: int = 30
    
    message: str = f"User: {name}, Age: {age}"
    detailed_message: str = f"User: {name.upper()}, Born: {2023 - age}"
    
    assert message == "User: Alice, Age: 30"
    assert "ALICE" in detailed_message
```

### 非効率なコレクション操作
```python
# BAD: 非効率・非Pythonic
def test_data_processing():
    numbers = [1, 2, 3, 4, 5]
    
    # 古いループスタイル
    squares = []
    for i in range(len(numbers)):
        squares.append(numbers[i] ** 2)
    
    # 非効率なフィルタリング
    evens = []
    for num in numbers:
        if num % 2 == 0:
            evens.append(num)
    
    # 手動での累積処理
    total = 0
    for num in numbers:
        total += num

# GOOD: Pythonic な記法
def test_data_processing():
    numbers: List[int] = [1, 2, 3, 4, 5]
    
    # リスト内包表記
    squares: List[int] = [num ** 2 for num in numbers]
    
    # filter() またはリスト内包表記
    evens: List[int] = [num for num in numbers if num % 2 == 0]
    
    # 組み込み関数使用
    total: int = sum(numbers)
    
    assert squares == [1, 4, 9, 16, 25]
    assert evens == [2, 4]
    assert total == 15
```

### contextmanager不使用
```python
# BAD: リソース管理が不適切
def test_file_processing():
    file = open("test.txt", "w")
    file.write("test data")
    file.close()                     # close()忘れのリスク
    
    file = open("test.txt", "r")
    content = file.read()
    file.close()

def test_database_transaction():
    conn = get_connection()
    try:
        cursor = conn.cursor()
        cursor.execute("INSERT INTO users VALUES (1, 'Alice')")
        conn.commit()
    except Exception:
        conn.rollback()              # 例外処理が複雑
    finally:
        conn.close()

# GOOD: contextmanager使用
def test_file_processing(tmp_path):
    test_file = tmp_path / "test.txt"
    
    # ファイル操作
    with test_file.open("w") as f:
        f.write("test data")
    
    with test_file.open("r") as f:
        content = f.read()
    
    assert content == "test data"

def test_database_transaction():
    with get_connection() as conn:
        with conn.cursor() as cursor:
            cursor.execute("INSERT INTO users VALUES (1, 'Alice')")
            # 自動的にcommit/rollback
```

### モダンなPython機能未使用
```python
# BAD: 古い記法
def test_data_handling():
    # 辞書のマージ（Python 3.9未満）
    dict1 = {"a": 1, "b": 2}
    dict2 = {"c": 3, "d": 4}
    merged = dict1.copy()
    merged.update(dict2)
    
    # Union型（Python 3.10未満）
    from typing import Union
    def process_value(value: Union[str, int]) -> str:
        return str(value)

# GOOD: モダンな記法
def test_data_handling():
    # 辞書のマージ（Python 3.9+）
    dict1: Dict[str, int] = {"a": 1, "b": 2}
    dict2: Dict[str, int] = {"c": 3, "d": 4}
    merged: Dict[str, int] = dict1 | dict2
    
    # Union型（Python 3.10+）
    def process_value(value: str | int) -> str:
        return str(value)
    
    assert merged == {"a": 1, "b": 2, "c": 3, "d": 4}
```

### Python品質メトリクス
```python
class PythonQualityMetrics:
    type_hint_coverage: float        # 型ヒントカバー率
    modern_syntax_usage: float       # モダン記法使用率
    f_string_ratio: float           # f-string使用率
    list_comprehension_ratio: float  # リスト内包表記使用率
    context_manager_usage: float     # contextmanager使用率
    
    def calculate_pythonic_score(self) -> float:
        """Pythonic度スコア（0-100）"""
        score = 0
        score += self.type_hint_coverage * 25      # 型ヒント重要
        score += self.modern_syntax_usage * 20     # モダン記法
        score += self.f_string_ratio * 20          # f-string
        score += self.list_comprehension_ratio * 15 # 内包表記
        score += self.context_manager_usage * 20   # リソース管理
        return min(score, 100)
```

### 自動修正機能
```python
class PythonModernizer:
    def modernize_string_formatting(self, code: str) -> str:
        """文字列フォーマットをf-stringに変換"""
        # % formatting → f-string
        code = re.sub(r'"([^"]*?)%s([^"]*?)" % \(([^)]+)\)', 
                     r'f"\1{\3}\2"', code)
        
        # .format() → f-string  
        code = re.sub(r'"([^"]*?)\{([^}]*?)\}([^"]*?)".format\(([^)]+)\)',
                     r'f"\1{\4}\3"', code)
        
        return code
    
    def add_type_hints(self, function_def: str) -> str:
        """関数に型ヒントを追加"""
        # AST解析で引数と戻り値の型を推論
        
    def modernize_loops(self, code: str) -> str:
        """ループをリスト内包表記に変換"""
        # for loop + append → list comprehension
```

### 設定可能項目
```yaml
python_quality_rules:
  type_hints:
    require_type_hints: true         # 型ヒント必須
    min_coverage: 0.8               # 最小カバー率
    strict_mode: false              # 厳密モード
    
  string_formatting:
    prefer_f_strings: true          # f-string推奨
    forbid_percent_formatting: true # %フォーマット禁止
    forbid_format_method: false     # .format()許可
    
  syntax_modernization:
    min_python_version: "3.9"       # 最小Pythonバージョン
    encourage_walrus_operator: false # := 演算子推奨
    encourage_union_types: true     # | 型記法推奨
    encourage_dict_merge: true      # | 辞書マージ推奨
    
  pythonic_patterns:
    prefer_comprehensions: true     # 内包表記推奨
    require_context_managers: true  # contextmanager必須
    encourage_builtin_functions: true # 組み込み関数推奨
    
  code_style:
    enforce_pep8: true              # PEP 8準拠
    max_line_length: 88             # 行長制限
    encourage_pathlib: true         # pathlibの使用推奨
```

### バージョン互換性チェック
```python
class VersionCompatibilityChecker:
    def check_python_version_features(self, code: str, min_version: str) -> List[Issue]:
        """Pythonバージョン固有機能をチェック"""
        issues = []
        
        if min_version < "3.6" and "f\"" in code:
            issues.append(Issue("f_string_not_supported", 
                               "f-strings require Python 3.6+"))
        
        if min_version < "3.9" and " | " in code:
            issues.append(Issue("dict_merge_not_supported",
                               "Dict merge operator requires Python 3.9+"))
        
        return issues
```

## 改善提案例
```
Python Quality Report (Score: 65/100):

Type Hints (Coverage: 40%):
- Missing type hints in 12 functions
- Add type hints for better IDE support and documentation

String Formatting (f-string usage: 30%):
- Line 10: "Hello %s" % name → f"Hello {name}"
- Line 15: "Age: {}".format(age) → f"Age: {age}"
- Line 20: Complex .format() call → f-string with expressions

Modern Syntax Opportunities:
- Line 25: for i in range(len(items)): → enumerate or direct iteration
- Line 30: Manual list building → list comprehension
- Line 35: dict.update() → dict merge operator (|)

Resource Management:
- Line 40: Missing context manager for file operations
- Line 45: Database connection not properly managed

Auto-modernize: Run `pytestee modernize --python` to apply fixes
Version check: Run `pytestee check --python-version 3.9` for compatibility
```

### 自動修正例
```python
# Before auto-modernization
def test_example():
    name = "Alice"
    message = "Hello %s, you are %d years old" % (name, 25)
    
    items = [1, 2, 3, 4, 5]
    squares = []
    for item in items:
        if item % 2 == 0:
            squares.append(item ** 2)

# After auto-modernization  
def test_example():
    name: str = "Alice"
    message: str = f"Hello {name}, you are {25} years old"
    
    items: List[int] = [1, 2, 3, 4, 5]
    squares: List[int] = [item ** 2 for item in items if item % 2 == 0]
```

## 優先度: MEDIUM
コード品質・保守性向上に寄与するが、機能への直接影響は少ない

🤖 Generated with [Claude Code](https://claude.ai/code)
